image: registry.gitlab.com/frnchfrgg/docker-web-ext

stages:
    - build
    - package

before_script:
    - yarn

.build_common: &build_common
    stage: build
    artifacts:
        paths:
            - dist/
        expire_in: 1 day

.zip_common: &zip_common
    stage: package
    script: yarn run build-zip
    artifacts:
        paths:
            - dist-zip/*.zip
        expire_in: 1 week

build:
    <<: *build_common
    allow_failure: true
    script: yarn run build

build:dev:
    <<: *build_common
    script: yarn run build:dev

zip:
    <<: *zip_common
    dependencies:
        - build

zip:dev:
    <<: *zip_common
    dependencies:
        - build:dev
